apiVersion: v1
kind: Namespace
metadata:
  name: flash-sale
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seckill-config
  namespace: flash-sale
data:
  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: "k8s"
  MYSQL_HOST: "mysql"
  MYSQL_PASSWORD: "123456"
  REDIS_HOST: "redis"
  REDIS_PASSWORD: "redis123"
  RABBITMQ_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: seckill-secret
  namespace: flash-sale
type: Opaque
stringData:
  mysql-password: "123456"
  redis-password: "redis123"
